<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

Source: https://machinelearningmastery.com/neural-networks-crash-course/

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

> Input layer, or the visible layer receives input from a dataset. This layer simply pass the input value though to the next layer.

### Hidden Layer:

> Not directly exposed to the input layer, in which they cannot be accessed except through the input layer.  We do not interact with them as they perform their functions. 

### Output Layer:

> The output layer is the final layer. The purpose is to output a value or vector in respect to the problem being solved. This layer is transformed by the "activation function" into a readable format for the context presented. 

### Neuron:

> The building blocks for NN. Neurons are simple computational units that have weighted input signals and produces an output signal using an activation function.

### Weight:

> Weight is the paramater within a NN that transforms input data within the networks hidden layer. For example, a single node may take the input data and multiply it by an assigned weight value, then add a bias before passing data to the next layer. 

### Activation Function:

> An activation function is a mapping of summed weighted input to the output of the neuron. This function governs the threshold on which the neuron is activated.

### Node Map:

> A visual representation of the internal architecture of a neural network; i.e. a map of the nodes (neurons) in the network and how they are connected to and share information with one another.

### Perceptron:

> The idea of the Perceptron is inspired by the information processing of a single neural cell called a neuron. 
  A neuron accepts input signals via its dentrites, which pass the electrical signal down to the cell body. 
  In a similar way, the Perceptron receives input signals from examples of training data that we weight and combined in a linear equation called the activator. 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?






#### Your Answer Here


> Input units receive various forms of information from the outside world. This in turn, triggers the hidden units(layers). The hidden layers in turn multiplies the inputs by the weights of the connection they travel along, and each unit is summed up along the way. If the sum reaches a certain threshold value, the unit 'fires' and triggers the units its connected to (going right). Finaly the information arrives to the output units. 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

>  a NAND gate (NOT-AND) is a logic gate which produces an output which is false only if all its inputs are true; thus its output is complement to that of an AND gate. 

The NAND gate (negated AND) gives an output of 0 if both inputs are 1, it gives 1 otherwise.

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [3]:
import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [3]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [ ]:
# Establish training data

np.random.seed(42)

# Input
# NAND gate features
X = np.array([[0,0],
              [1,0],
              [0,1],
              [1,1]], dtype=float)

# Outputs
# 0 if both inputs are 1, 1 otherwise.
y = np.array([[1],
              [1],
              [1],
              [0]], dtype=float)

In [ ]:
# Sigmoid activation function and its derivative for updating weights

def sigmoid(X: float) -> float:
    return 1 / (1 + np.exp(-X))


def sigmoid_derivative(X: float) -> float:
    return sigmoid(X) * (1 - sigmoid(X))

In [ ]:
# random weights btw 0 and 1 for two inputs

w = 2 * np.random.random((2,1)) - 1
w

In [ ]:
# Calculate weighted sum of inputs and weights
z = np.dot(X, w)

# Output the activated value for the end of 1 training epoch
sigmoid(z)
print(sigmoid(z))

output = sigmoid(z)

In [ ]:
error = y - output
error

In [ ]:
adjustments = error * sigmoid_derivative(output)
adjustments

In [ ]:
#with the adjustments determined, we can apply them to our original weights
w += np.dot(X.T,adjustments)

In [ ]:
w

In [4]:
# Bringing it all together

inputs = np.array([
              [0,0,1],
              [1,0,1],
              [0,1,1],
              [1,1,1]], dtype=float)

# Outputs
# 0 if both inputs are 1, 1 otherwise.
correct_outputs = np.array([[1],
                            [1],
                            [1],
                            [0]], dtype=float)


In [7]:
# Generatings weights btw 0 and 1
weights = 2 * np.random.random((3,1)) - 1

# Sigmoid activation function and its derivative for updating weights

def sigmoid(X: float) -> float:
    return 1 / (1 + np.exp(-X))


def sigmoid_derivative(X: float) -> float:
    return sigmoid(X) * (1 - sigmoid(X))

In [8]:


#now we can iterate across this to increase our accuracy
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-11.84031106]
 [-11.84031106]
 [ 17.80933098]]
Output after training
[[0.99999998]
 [0.99744952]
 [0.99744952]
 [0.00281159]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [4]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [37]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

# pipe
pipe = make_pipeline(
    MinMaxScaler() # change values to be represented between 0 and 1
)

# split features and targets
target = 'Outcome'
X = diabetes.drop(target, axis=1)
y = diabetes[target]

In [15]:
print(X.shape)
print(y.shape)

(768, 8)
(768,)


In [16]:
# apply pipe
X = pipe.fit_transform(X)
print(f"""X Shape: {X.shape}
""")

X Shape: (768, 8)



In [17]:
# cast y as np.array for modeling
y = np.array(y)

# reshape into a column vector, do the same for y_test if you want to evaluate on test set
# https://stackoverflow.com/questions/17428621/python-differentiating-between-row-and-column-vectors
y = y.reshape((-1,1))
y

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [18]:
# Set the random seed for reproducible work
np.random.seed(42)

In [19]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [20]:
weights = 2 * np.random.random((8,1)) - 1

In [24]:
(len(diabetes.columns) - 1)

8

In [22]:
weights

array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788],
       [ 0.19731697],
       [-0.68796272],
       [-0.68801096],
       [-0.88383278],
       [ 0.73235229]])

In [23]:
weighted_sum = np.dot(X, weights)
print(weighted_sum.shape)
weighted_sum[:8]

(768, 1)


array([[ 0.72770517],
       [ 0.4253715 ],
       [ 0.62546723],
       [ 0.28709139],
       [-0.42362373],
       [ 0.53403584],
       [ 0.17043598],
       [ 0.08789057]])

In [27]:
activated_output = sigmoid(weighted_sum)
print(activated_output.shape)
activated_output[:8]

(768, 1)


array([[0.67430149],
       [0.60476789],
       [0.65146096],
       [0.57128391],
       [0.39564995],
       [0.63042391],
       [0.54250615],
       [0.52195851]])

In [28]:
error = y - activated_output
print(error.shape)
error[:10]

(768, 1)


array([[ 0.32569851],
       [-0.60476789],
       [ 0.34853904],
       [-0.57128391],
       [ 0.60435005],
       [-0.63042391],
       [ 0.45749385],
       [-0.52195851],
       [ 0.3047327 ],
       [ 0.23904435]])

In [29]:
adjustments = error * sigmoid_derivative(weighted_sum)
print(adjustments.shape)
adjustments[:10]

(768, 1)


array([[ 0.07152958],
       [-0.14455385],
       [ 0.07913913],
       [-0.13991806],
       [ 0.14450679],
       [-0.14688222],
       [ 0.11354687],
       [-0.13023795],
       [ 0.06456393],
       [ 0.04348268]])

In [30]:
weights += np.dot(X.T, adjustments)
print(weights.shape)
weights

(8, 1)


array([[ -7.10068393],
       [-20.90491981],
       [-24.93214537],
       [ -7.91118561],
       [ -3.12125496],
       [-19.20088876],
       [ -5.70916108],
       [ -5.39533818]])

In [31]:
X.T.shape

(8, 768)

In [32]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(X, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = y - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(X.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ -7.10057238]
 [-20.90488362]
 [-24.93214537]
 [ -7.91118561]
 [ -3.12125496]
 [-19.20088734]
 [ -5.70914668]
 [ -5.39530562]]
Output after training
[[4.62607167e-22]
 [1.23390019e-15]
 [3.67844445e-20]
 [2.31907797e-15]
 [3.55757796e-20]
 [3.71487252e-17]
 [9.55603624e-15]
 [1.51649789e-12]
 [7.59146676e-24]
 [7.48059849e-18]
 [8.84721377e-20]
 [1.72844222e-22]
 [3.36914518e-22]
 [1.42414757e-22]
 [1.87464344e-21]
 [3.80474917e-11]
 [3.78918322e-22]
 [1.06045237e-17]
 [1.10718970e-15]
 [9.06503025e-19]
 [2.07299462e-22]
 [5.21058156e-20]
 [4.76812750e-25]
 [3.24473773e-20]
 [7.11639948e-25]
 [2.53196006e-20]
 [2.15469425e-21]
 [2.72509868e-15]
 [3.72891588e-22]
 [2.59433230e-20]
 [1.17203168e-20]
 [6.94152265e-22]
 [3.19085251e-14]
 [4.85471394e-17]
 [6.23407963e-21]
 [2.54600877e-17]
 [8.48711165e-21]
 [9.95880424e-21]
 [4.04392094e-18]
 [3.09632104e-22]
 [9.09578044e-21]
 [8.55471081e-22]
 [1.15501054e-19]
 [9.42141358e-29]
 [2.63171078e-19]
 [1.90315796e-23

In [33]:
# pull values out of lists and append into a single list with a for loop
pred = []
for x in activated_output:
  for x in x:
    pred.append(int(round(x,1)))

In [34]:
pred

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [35]:
# Change values to 1 or 0 depending on the threshold (0.5) with a single nested list comprehension if not using for loop
y_pred = [1 if x > 0.5 else 0 for x in [x for x in activated_output]]

# Use np.where to define a condition and the desired outputs, like using an if/else
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html
y_pred = np.where(activated_output > 0.5, 1, 0)

In [38]:
accuracy_score(y, y_pred)

0.6510416666666666

In [9]:
class Perceptron(object):
    
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter
        
    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # weights
        self.weight = np.zeros(1 + X.shape[1])

        # Number of misclassifications
        self.errors = []  # Number of misclassifications

        for i in range(self.niter):
          err = 0
          for xi, target in zip(X, y):
            delta_w = self.rate * (target - self.predict(xi))
            self.weight[1:] += delta_w * xi
            self.weight[0] += delta_w
            err += int(delta_w != 0.0)
          self.errors.append(err)
        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weight[1:]) + self.weight[0]

    def predict(self, X):
        """Return class label after unit step"""
        """ Default Step Function"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

In [ ]:
# Instance of the Class
test = Perceptron()

# Fit
test.fit(X, y)

# Predict (Returns a list of predictions)
y_pred = test.predict(X)

# Score
accuracy_score(y, y_pred)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?